# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Docker - Project Poseidon

on:
  push:
    branches: [ "master", "dev_sroy" ]
  pull_request:
    branches: [ "master" ]
  schedule: ## Schedule the job to run at 6AM daily.
    - cron: '0 4 * * *'

permissions:
  contents: write

jobs:
  playwright:
    name: Docker - Test Parabank with Allure Report
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.1-focal

    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r local-requirements.txt
        pip install -e .
    - name: Install the browsers for playwright
      run: |
        python -m playwright install --with-deps
    - name: Test with pytest
      run: |
        pytest web/src/test/testcases/youtube/
    - name: Allure gh-page Checkout
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        # python -m pip install --upgrade pip
        # python -m pip install pytest-playwright
        # python -m pip install pytest
        # python -m pip install pytest-xdist
        # python -m pip install allure-pytest